# Generated by Django 6.0 on 2026-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='mode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
