# Generated by Django 6.0 on 2026-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewresult_difficulty_interviewresult_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='voice_confidence',
            field=models.IntegerField(default=0),
        ),
    ]
